/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-09-08 00:53:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.senai.model.Pessoa;

public final class alterarSenha_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1630352853772L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.senai.model.Pessoa");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/estilo.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("ul {\r\n");
      out.write("	background-color: #eee;\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("li {\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("li a {\r\n");
      out.write("	color: black;\r\n");
      out.write("	padding: 16px;\r\n");
      out.write("	display: block;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("li a:hover {\r\n");
      out.write("	background-color: #ddd;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<ul>\r\n");
      out.write("	<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("	<li><a href=\"form-cadastro.jsp\">Cadastro</a></li>\r\n");
      out.write("	\r\n");
      out.write("	");

	Pessoa usuario = (Pessoa) request.getSession().getAttribute("usuario");
	boolean verLista = false;
	if (usuario != null) {
		verLista = true;
	
      out.write("\r\n");
      out.write("	<li><a href=\"login?acao=sair\">Logout</a></li>\r\n");
      out.write("	<span id=\"dadosUsuario\">Bem vindo:");
      out.print(usuario.getNomeCompleto());
      out.write("</span>\r\n");
      out.write("	<li><a href=\"alterarSenha.jsp\">Alterar senha</a></li>\r\n");
      out.write("	");

	} else {
	
      out.write("\r\n");
      out.write("	<li><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("</ul>");
      out.write('\r');
      out.write('\n');

	if(usuario == null){
		response.sendRedirect("form-cadastro.jsp");
	}

      out.write("\r\n");
      out.write("    <fieldset>\r\n");
      out.write("        <legend id=\"msg\" name=\"msg\">Altere sua senha</legend>\r\n");
      out.write("        <img id=\"img-java\" src=\"img/java.png\" alt=\"imagem java\">\r\n");
      out.write("        <label for=\"senhaAtual\">Senha Atual</label>\r\n");
      out.write("        <input class=\"larguraTexto\" type=\"password\" name=\"senhaAtual\" id=\"senhaAtual\">\r\n");
      out.write("        <label for=\"novaSenha\">Nova Senha:</label>\r\n");
      out.write("        <input class=\"larguraTexto\" type=\"password\" name=\"novaSenha\" id=\"novaSenha\">\r\n");
      out.write("        <label for=\"confSenha\">Confirmar Senha:</label>\r\n");
      out.write("        <input class=\"larguraTexto\" type=\"password\" name=\"confirmarSenha\" id=\"confirmarSenha\">\r\n");
      out.write("        <input type=\"submit\" class=\"bt\" value=\"Alterar\" onclick=\"alterarSenha()\">\r\n");
      out.write("        <span style=\"background-color: blue; color: #fff;\" id=\"msg\"></span>\r\n");
      out.write("    </fieldset>\r\n");
      out.write("    \r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("		\r\n");
      out.write("		function alterarSenha(){\r\n");
      out.write("			var senhaAtual = document.getElementById(\"senhaAtual\").value;\r\n");
      out.write("			var novaSenha = document.getElementById(\"novaSenha\").value;\r\n");
      out.write("			var confirmarSenha = document.getElementById(\"confirmarSenha\").value;\r\n");
      out.write("			\r\n");
      out.write("			var parametros = \"senhaAtual=\"+senhaAtual;\r\n");
      out.write("			 parametros += \"&novaSenha=\"+novaSenha;\r\n");
      out.write("			 parametros += \"&confirmarSenha=\"+confirmarSenha;\r\n");
      out.write("			 acessarApi(parametros);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function acessarApi(parametros){\r\n");
      out.write("			const api = new XMLHttpRequest();\r\n");
      out.write("			api.open(\"POST\",\"http://localhost:8080/form-cadas-pessoa/alterarSenha\");\r\n");
      out.write("			api.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\r\n");
      out.write("			api.send(parametros);\r\n");
      out.write("			api.onload = function() {\r\n");
      out.write("				document.getElementById(\"msg\").innerHTML = this.responseText;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
